### ISSUE TITLE
Modify naming convention for RRFS retro verification 

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#101]
RRFS retro modelers discussed the RRFS retro verification in this week's DA meeting and the workflow for running retro cases seems to have solidified, meaning we can make "permanent" changes to our configuration conventions to match. Right now the forecast path and names in RRFS UPP are different from that in verification scripts, so they link the RRFS files to the names used in verification scripts to do verification. 

For example, 
in RRFS UPP, grib2 files like **RRFS_conus_3km.${yyyymm}${dd}/${hh}/RRFS_CONUS.t${hh}z.bgdawpf0${fcst}.tm00.grib2**
in MATS scripts, it asks files like **${yyyymm}${dd}/${hh}/postprd/RRFS_CONUS.t${hh}z.bgdawp${fcst}.tm${hh}**

They would like to change the path and file names in our configuration to match RRFS UPP grib2 files so that they can stop doing this extra link step.

**Comment by JeffHamiltonNOAA** [comment]
Now that all processing of old RRFS retros has been completed, this will once again become my top priority after the VxIngest Milestone 1.5 review.

**Comment by JeffHamiltonNOAA** [comment]
This issue continues to be a thorn that won't go away. There are still a number of different RRFS versions across Jet and Hera, with different naming conventions and directory structures, along with output grids to be used in verification. I've created a document to log exactly where things stand for all versions of RRFS on both machines. I'll compile the information there and then engage with the modelers in order to see what should be the standard moving forward, both from a modeler and verification standpoint.

https://docs.google.com/document/d/1d35YEup2JPYCN8fBD9ICsy8uJ05Nn7Nlw5gB2q232VM/edit?usp=sharing

**Comment by bonnystrong** [comment]
The priority should be changed from "Don't use: Blocker".  High?

**Comment by bonnystrong** [comment]
Or are we moving away from Labels to identify priorities?

**Comment by JeffHamiltonNOAA** [comment]
Yet another wrinkle to this is that isobaric and native files in some retros are using different naming conventions. I've added this to the document and plan to send it to Curtis, Steve, and Terra later this week

**Comment by JeffHamiltonNOAA** [comment]
With all of the Jet issues over the past weeks, I have downgraded this issues priority until I can properly use the system to better investigate these inconsistencies. Hopefully next week

**Comment by JeffHamiltonNOAA** [comment]
All verification scripts are now complaint with the latest versions of RRFS retros that I know of. That is not to say that things won't change in the future, but I'll create new issues for that. This can be closed
