### ISSUE TITLE
Investigate rotated lat-lon domain capability with MET utilities

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#103]
Curtis is attempting to facilitate a knowledge transfer between GSL and EMC for processing the full rotated lat-lon domains of the RAP and RRFS_NA models. Specifically, he has mentioned using Python, NCL, and/or METplus to verify and plot the domain. For my part, investigate if METplus can use the full RAP rotated lat-lon domain, as it is a special case that is not compatible with many projection packages that we have attempted to use over the years.

**Comment by JeffHamiltonNOAA** [comment]
when running the pcp_combine tool using MET 10.1.0, the utilitity did not recognize the native RAP grid. Not a good sign, but this may not be the case for the more verification centric MET tools. I'll attempt with grid_stat, and if that doesn't work, we'll know.

**Comment by JohnHalleyGotway** [comment]
@JeffHamiltonNOAA can you please point me to a sample data file I can use for testing?

**Comment by JeffHamiltonNOAA** [comment]
Updates from conversation with the DTC:

Using 10.1.0 utilities, I am getting an unrecognized grid error when trying to process the full RAP rotated lat-lon grid:

MetGrib2DataFile::read_grib2_grid() -> found unrecognized grid definition (32769)

This occurs when I attempt to use GridStat and PCP_Combine on Jet, in the /lfs4/BMC/amb-verif/hamilton directory, with the following commands:

/contrib/met/10.1.0/bin/grid_stat 2209006000006 st4_pr.2022033112.06h.grb2 GridStatConfig
/contrib/met/10.1.0/bin/pcp_combine -name APCP -add 2208912000001 1 test.nc

I'll admit that I have never attempted to use the full RAP grid before, and that the grid itself is a bit strange even for a rotated lat-lon. I should note that the experimental RRFS_NA_3km, also a rotated lat-lon, works just fine with the following command in the same directory:

/contrib/met/10.1.0/bin/grid_stat RRFS_NA_3km.t11z.bgsfcf001.tm00.grib2 st4_pr.2022033112.01h.grb2 GridStatConfig_RRFS_NA

I know that the wgrib2 utility has never agreed with RAP data well, failing to recognize exactly what it is. Perhaps this is a similar problem

**Comment by JeffHamiltonNOAA** [comment]
John H.G. responded that the RAP grid is not supported by METplus at this time, and will need to be enhanced in an upcoming version in order to satisfy this requirement. This issue can now be closed since ongoing discussions with the DTC will be recorded in their GitHub repository
