### ISSUE TITLE
Backfill RAP_OPS and HRRR_OPS ceiling verification

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#107]
In order to remove the ceiling clear sky default bug that was uncovered last month from our long term statistics, I will be backfilling operational RAP and HRRR back to December of 2020 (the last NCO implementation). Work to reprocess the observations correctly, then reverify the two operational models over this period using the backfilling scripts.

**Comment by bonnystrong** [comment]
Stan was user asking for this.  Huge effort requiring lots of resources.

**Comment by mollybsmith-noaa** [comment]
No longer relevant
