### ISSUE TITLE
Epic: Set up developer tooling and CI

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#135]
We want to set up CI for VXingest in a similar manner to the way MATS is set

See:
- [x] #136
- [x] #40 
- [x] #73

**Comment by bonnystrong** [comment]
Needs to be addressed by Jeff together with Randy and Ian.  Do this after other features for Milestone 2.0 completed.

Needs to happen on HPC.

Ian could start working on this while Jeff is unavailable, working on the tools.  Need to identify entry points.
