### ISSUE TITLE
Experiment with adding a 3-D component to the CB Data Model

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#144]
In order to create the Upper Air application, we will need to add a vertical component to the data section of our documents. Experiment with different ways of accomplishing this, but it should not require changing anything in regards to document metadata or ID.

**Comment by JeffHamiltonNOAA** [comment]
Discussed concepts at the ingest meeting. We will include interpolated height and mandatory pressure levels (determined by us, similar to legacy) in every document, but split documents by pressure level to avoid adding another nest to the data object, making them too large to handle efficiently. Below is a concept of what this will look like in a model document.

We will focus on improving queries and indexing first, but consider splitting out stations based on geographic and/or political boundaries to improve performance. This is a last resort, as we would need to do this for surface/ceiling/visibility pairs as well in order to remain consistent

Sample Model Document
{
  "correctedTime": "",
  "units": {
    "DewPoint": “degrees F”,
    “Height”: “meters”,
    "Temperature": “degrees F”,
    “Specific Humidity”: “g/kg”,
    "RH": “percent”,
    “RHot”: “percent”,
    "WD": “degrees”,
    "WS": “mph”,
    “Uwind”: “m/s”,
    “Vwind”: “m/s”
  },
  "dataSourceId": "NCO",
  "docType": "model",
  "model": "HRRR_OPS",
  "fcstValidISO": "2021-07-01T00:00:00",
  "fcstValidEpoch": 1625097600,
  "fcstLen": 0,
  "id": "DD:V01:RAOB:HRRR_OPS:500:1625097600:0",
  "subset": “RAOB”,
  "type": "DD",
  "version": "V01",
  “level”: “500”,  
  "data": [{
    "DewPoint": ,
    “Height”: ,
    "Temperature": ,
    “Specific Humidity”: ,
    "RH": ,
    “RHot”: ,
    "WD": ,
    "WS": ,
    “Uwind”: ,
    “Vwind”: ,
    "name": “KDEN”
  }, {
    "DewPoint": ,
    “Height”: ,
    "Temperature": ,
    “Specific Humidity”: ,
    "RH": ,
    “RHot”: ,
    "WD": ,
    "WS": ,
    “Uwind”: ,
    “Vwind”: ,
    "name": “KBOU”
  } … ]
}

**Comment by bonnystrong** [comment]
U and V wind components - what units to store in db?  Consensus is meters/sec.  

Move everything to SI units now.

**Comment by JeffHamiltonNOAA** [comment]
Updated Model Document
{
"correctedTime": "",
"units": {
"DewPoint": “degrees C”,
“Height”: “meters”,
"Temperature": “degrees C”,
“Specific Humidity”: “g/kg”,
"RH": “percent”,
“RHot”: “percent”,
"WD": “degrees”,
"WS": “m/s”,
“Uwind”: “m/s”,
“Vwind”: “m/s”,
“Level”: “mb”
},
"dataSourceId": "NCO",
"docType": "model",
"model": "HRRR_OPS",
"fcstValidISO": "2021-07-01T00:00:00",
"fcstValidEpoch": 1625097600,
"fcstLen": 0,
"id": "DD:V01:RAOB:HRRR_OPS:500:1625097600:0",
"subset": “RAOB”,
"type": "DD",
"version": "V01",
“level”: “500”,
"data": [{
"DewPoint": ,
“Height”: ,
"Temperature": ,
“Specific Humidity”: ,
"RH": ,
“RHot”: ,
"WD": ,
"WS": ,
“Uwind”: ,
“Vwind”: ,
"name": “KDEN”
}, {
"DewPoint": ,
“Height”: ,
"Temperature": ,
“Specific Humidity”: ,
"RH": ,
“RHot”: ,
"WD": ,
"WS": ,
“Uwind”: ,
“Vwind”: ,
"name": “KBOU”
} … ]
}

**Comment by JeffHamiltonNOAA** [comment]
Add height for both AGL and MSL and keep entries for all stations inside the data object. We will figure out how to properly extract stations from large amounts of documents at a later time. Molly will schedule a meeting specifically for this.

**Comment by randytpierce** [comment]
I feel that this is complete by the work that has been done on the builders. I am closing this issue.
