### ISSUE TITLE
Add RI verification to realtime TC ingest

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/VxIngest#146]
The global group has requested that we add in RI verification to our realtime TC workflow.

**Comment by mollybsmith-noaa** [comment]
Everything is roughly set up for this but it still needs testing. Luckily, Hurricane Darby in the Pacific just rapidly intensified, so I don't have to go hunt down a case from last year! The Atlantic is still very quiet.

**Comment by mollybsmith-noaa** [comment]
Jet was down so much this week I couldn't really work on this at all. Apparently, while my grid-to-grid and MODE ingests live on /lfs4, this one is still /lfs1, which is where the problems are :(

**Comment by bonnystrong** [comment]
Blocked by problems on jet

**Comment by mollybsmith-noaa** [comment]
Blocked until I can write a workaround for the issues that I will describe in https://github.com/NOAA-GSL/VxIngest/issues/148

**Comment by mollybsmith-noaa** [comment]
I finally had time to work on this, so it's all functional now and I'm in the process of backfilling. It'll be ready and waiting when next hurricane season rolls around, although by necessity we need to verify RI at a 7-day lag.

**Comment by mollybsmith-noaa** [comment]
This is all set to go. Currently we can't store RI ctc stats in the METplus database, but I'm talking to John HG about how we might change that,
