### ISSUE TITLE
Reduce number of slurm jobs

### ISSUE THREAD

**Issue by bonnystrong** [NOAA-GSL/VxIngest#149]
From team meeting notes July 27, 2022:
"Big item from Dave/Curtis: too many slurm jobs on jet!  Amb-verif is submitting 46% of the jobs, but using only 0.1% of the core hours.  This is stressing the system, and Curtis has asked that we try to combine jobs somehow so we can reduce the number we execute by at least x2 (ideally x10 – this is my goal)
From David Dowell: we can reduce any HRRRE jobs from the crontab – that model is not being run anymore.
MODE and Ensemble applications have added many jobs
Jeff can make some changes in current jobs; Molly can make some changes in grid-to-grid"

- [x] #151
- [ ] #154 (Molly)

There's no doing anything with our TC workflow, as that one already runs everything out of a single slurm job, or MODE, which I suspect will cause Jet to combust if I try to combine anything.

**Comment by mollybsmith-noaa** [comment]
I'm un-assigning myself from this issue because my portion of it has been completed.

**Comment by mollybsmith-noaa** [comment]
Accidentally closed the issue, realized my mistake, and re-opened it. Sorry about that!

**Comment by JeffHamiltonNOAA** [comment]
Closing. See issue #151 for details
