### ISSUE TITLE
Ensure all partial sums are available for all models

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/VxIngest#15]
In our current partial sums tables, there's some inconsistency between models. We want to make sure that in the new schema, all models make use of all fields.

**Comment by mollybsmith-noaa** [comment]
To be specific, here are the essential five sums needed for each model:

1. sum( (model - obs)^2 )
2. sum( N )
3. sum( (model - obs) )
4. sum( model )
5. sum ( obs)

If we want to calculate MAE, we need a sixth sum:

6. sum( abs(model - obs) )

*NOTE: MATS tends to use obs - model instead of model - obs. Both work, although I would suggest that the latter is favorable.

**Comment by davidturner53** [comment]
Good list, Molly.  I propose we store all 6 of these sums for any continuous variable.

**Comment by bonnystrong** [comment]
This is only for new Couchbase schema?
@JeffHamiltonNOAA From notes on July 27, 2022: "Jeff could implement a fix to do it right - standardize upper air database tables and fill necessary fields."  Any plans to do that or is Molly's workaround good enough for now?

**Comment by randytpierce** [comment]
I included this list in the README.md for the vxIngest PartialSumsBuilder

**Comment by randytpierce** [comment]
I have implemented this in github branch 197-create-a-partial_sums_to_cb-directory-and-structure-that-is-based-on-the-existing-ctc_to_cb-directory-structure-in-vxingest which is in the process of being merged to main today. Closing this issue.
