### ISSUE TITLE
 Visibility documents not being properly handled by ingest

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#158]
Since we implemented the visibility documents in the ingest process, visibility documents are not being properly handled by either the ingest or the import script.

This is easily discovered by looking at the type "DD" documents in the database.

To debug the problem it is necessary to disable the cronjobs that ingest and also import the data, then run the cronjob by hand and monitor log files etc.

The problem is complicated by the way the ingest and import scripts clean up after themselves, so this  code needs to be improved. The problem is also complicated by the quantity of data so the ingest options of setting a start and end epoch also need to be carried forward to the main script entry point.

What should happen is both VISIBILITY and CEILING documents should be ingested and imported within a single ingest job spec. This is the first time we have tried doing that which is why the bug is only now discovered.

So far I have determined that there was a subtle problem with the ingest code itself having to do with how the ingest template parameters are initialized within each ingest thread. Fixing this has resulted in getting the correct data decoded but there is still a problem with actually producing the correct output files.

The first problem was severe enough that it brought into question the validity of some of the existing CEILING data. I couldn't determine exactly which data was potentially bad so I have disabled the ingest and am reprocessing the entire data set.

**Comment by randytpierce** [comment]
I have set the priority of this bug to "blocker" because until it is fixed the ingest is stopped.

**Comment by bonnystrong** [comment]
Bug has been fixed.  Ingest took over 5 days.  Import took only a few minutes.  Metadata update took  about 15 mins.
