### ISSUE TITLE
blow away the metar_legacy and legacy_retro data

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#162]
Creating an issue so that I don't forget to do this....
blow away the metar_legacy and legacy_retro data from the couchbase data

**Comment by bonnystrong** [comment]
Should do this before reload of data in new model.

**Comment by bonnystrong** [comment]
Molly: please watch the cb ceiling metadata and be sure it is correct.

**Comment by randytpierce** [comment]
This is done.
