### ISSUE TITLE
modify all the data in the mdata bucket to match the schema currently in mdatatest

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#167]
The mdatatest bucket has the data array transformed into a data map. This means in order to make everything work now, we need to modify the existing data. To do this we need to stop the ingest cron jobs, do the export import and then restart the ingest.

This implies that we first have the ingest code (and the mats couchbase connection code) modified to work with the new data structure.

**Comment by hourglassnebula** [comment]
I have checked-in changes to upload code at: VxIngest/scripts/VXingest_utilities/share/SchemaTests.  The final bucket name will now be 'vxdata', scope _default, and collection METAR.  Also, no idx0 field will be generated, and any 'subset' : 'metar'
will be converted to 'subset' : 'METAR'.  I will do a small subset when we are ready to upload to make sure everything is working fine.

**Comment by randytpierce** [comment]
We are taking a slightly different approach with this. We are naming the new bucket vxdata and leaving mdata intact for a while so that we can validate data and queries.

**Comment by randytpierce** [comment]
The ingest code is finished and the upload is essentially ready, we will run it tonight. Once that finishes and we validate the data in the new 'vxdata' bucket we can close this issue.

**Comment by bonnystrong** [comment]
Still working on "small things".

Bonny: higher priority than anything else.

**Comment by randytpierce** [comment]
this is finished now
