### ISSUE TITLE
Create retro global grid-to-grid workflow

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/VxIngest#17]
The global group needs a way to compare their retro models with production ones via global grid-to-grid verification.

**Comment by bonnystrong** [comment]
Could you indicate in the issue what is blocking it?  What needs to happen in order to work on this?

**Comment by mollybsmith-noaa** [comment]
Everything is done except for the code to load retro verification into the database. The global group needs to provide me with test data for this, but have not done so.

**Comment by mollybsmith-noaa** [comment]
The retro workflow is complete, and Hongli is testing it.
