### ISSUE TITLE
Revisit using full text geo search now that we have the data in a dictionary instead of a list

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#172]
There is a reasonable chance that now that the couchbase sdk is 4.x and now that we have our data in a map instead of a list that the full text geo search may work for us again. We need to investigate this and start using it if it is available.

**Comment by randytpierce** [comment]
This is important but not high enough priority to put in progress

**Comment by randytpierce** [comment]
This might be able to be addressed in the PartialSumsBuilder work covered in issue https://github.com/NOAA-GSL/VxIngest/issues/197

**Comment by mollybsmith-noaa** [comment]
Issue is no longer relevant.
