### ISSUE TITLE
design and code the ingest process for 3D upperair model ingest

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#179]
We need to design and code the ingest processing for upperair model data. This ingest will take extract data from grib2 model output files and import it into couchbase documents using the VXingest processing that currently exists for METAR data and adding to it the necessary builder classes for upperair 3D data. Refer to the design plan [document](https://docs.google.com/document/d/1-L-1FMKGDRXNGmAZhdZb3_vZT41kOWte8ufqd2c_CvQ/edit?usp=sharing
) 

The code will be kept in the feature_3D branch.

It is expected that the following subtasks will need to be done. This task list will probably need to be expanded.
### Tasks

https://github.com/NOAA-GSL/VxIngest/issues/179#tasklist-block-957f3a97-a627-46ad-9e78-e24620639017

**Comment by randytpierce** [comment]
placing this temporarily on hold until I get a better understanding of how to interpolate the levels.

**Comment by JeffHamiltonNOAA** [comment]
This is a duplicate issue with #180. Closing this one
