### ISSUE TITLE
design and code the ingest processing for upperair observation data

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#180]
We need to design and code the ingest processing for upperair observation data. This ingest will take extract data from the GSL https://ruc.noaa.gov/raobs/intl website and import it into couchbase documents using the VXingest processing that currently exists for METAR data and adding to it the necessary builder classes for upperair 3D data. Refer to the design plan [document](https://docs.google.com/document/d/1-L-1FMKGDRXNGmAZhdZb3_vZT41kOWte8ufqd2c_CvQ/edit?usp=sharing)

The code will be kept in the feature_3D branch.

It is expected that the following subtasks will need to be done. This task list will probably need to be expanded.
### Tasks

https://github.com/NOAA-GSL/VxIngest/issues/180#tasklist-block-4b836e24-34bb-4811-8824-acbf5c01b05e

```[tasklist]
### Tasks
- [ ] deal with unknown stations.
```

**Comment by randytpierce** [comment]
This is progressing nicely but I need a better understanding of how to interpolate the levels in the API so I am putting this as blocked for the time being.

**Comment by ian-noaa** [comment]
We're now thinking it would be best to ingest the prepbufr data instead of pulling from the old RAOB database.

**Comment by ian-noaa** [comment]
Blocked waiting on the cfgrib implementation in #226

**Comment by JeffHamiltonNOAA** [comment]
I believe that this issue can be closed as we have moved completely in the prepBUFR direction
