### ISSUE TITLE
Create ingest and JOB documents for the upperair model ingest.

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#182]

**Comment by randytpierce** [comment]
In order to actually run the ingest and complete the handler code we need to create the actual ingest and job documents. This goes hand in hand with the code development so both are open simultaneously.

**Comment by bonnystrong** [comment]
Depends on decisions on levels.

**Comment by bonnystrong** [comment]
Randy is doing this as he goes.

**Comment by randytpierce** [comment]
I've created the initial docs, and a mnemonic-mapping document and they are in the RAOB collection.
