### ISSUE TITLE
Provide documentation on partial sums tables

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#189]
Randy, Ian, and Gopa are going to move forward with adding a partial sums builder to the new ingest with assistance from Jeff and Molly. Provide them with documentation on how the SQL tables work and how calculations are pieced together from the components

**Comment by bonnystrong** [comment]
It's here: [](https://docs.google.com/document/d/1i2JJ_T_CsTRWxzlOWFWGWhGxyhEoVBjPeIJb1_CtWdo/edit?usp=sharing)

**Comment by JeffHamiltonNOAA** [comment]
I've created the document but it does require a bit more polishing and statistical explanation

https://docs.google.com/document/d/1i2JJ_T_CsTRWxzlOWFWGWhGxyhEoVBjPeIJb1_CtWdo/edit?usp=sharing

**Comment by JeffHamiltonNOAA** [comment]
This issue can be closed. The document is turning into a working document that will store SQL partial sum information along with the new Couchbase versions
