### ISSUE TITLE
Create and load JSON files for GUI metadata reference documents

### ISSUE THREAD

**Issue by venitahagerty** [NOAA-GSL/VxIngest#19]
Based on the existing GUI metadata reference tables in MATS and Molly's GUI metadata Google doc, create JSON files for GUI metadata reference documents and load them into Couchbase.

https://docs.google.com/document/d/1PhhfHaXxaJW5klC8c6Ny6y1XkU25Z-u_Yq9IAf2Df4I/edit

**Comment by randytpierce** [comment]
These documents were created and provided to necessary people.
