### ISSUE TITLE
Add canned test data load script to cb_evaluation_tests Couchbase test framework

### ISSUE THREAD

**Issue by gopa-noaa** [NOAA-GSL/VxIngest#201]
We need a place to store canned test data
Script will load canned test data and then will run the setup script to create required indices, so that evaluation tests will run with predictable  and testable results.

**Comment by gopa-noaa** [comment]
I plan to start working on this, will discuss at the dev meeting ....

**Comment by mollybsmith-noaa** [comment]
No longer relevant.
