### ISSUE TITLE
Create realtime AMDAR PBLH ingest

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/VxIngest#207]
We need to create a realtime METplus-based workflow for Jason's AMDAR PBLH stats. This shouldn't be too difficult. For the most part we can copy our global grid-to-grid workflow, change the data paths, and write a new wrapper script calling the appropriate python commands.

**Comment by mollybsmith-noaa** [comment]
Status update: The scalar stat verification workflows that we have were upgraded to MET 11 with no trouble whatsoever, so I've started creating a MET 11 workflow to run Jason's scripts in realtime.

**Comment by mollybsmith-noaa** [comment]
Everything is set up correctly, but the python embedding is throwing segfaults. Yay.

**Comment by bonnystrong** [comment]
Can't find a python env that has netcdf4

**Comment by mollybsmith-noaa** [comment]
Running with the newest versions of MET and METplus (11.1.0 and 5.1.0) fixed the segfault! They weren't available on Jet until yesterday so using them hadn't been an option, but I had thought that this use case was developed with the prior versions (11.0.1 and 5.0.1) and thus it wouldn't be necessary. Apparently not. John HG is looking into how to have a better error message and no segfault in the future.

**Comment by mollybsmith-noaa** [comment]
This ran successfully for most of Friday and then stopped right when I left to enjoy the three-day weekend.

**Comment by mollybsmith-noaa** [comment]
Good news! This workflow actually *has* been running successfully, but the stats produced aren't being loaded into the database because we as of yet have no conda with which to load them. Once Jeff has conda working again we can backfill all the stats.
