### ISSUE TITLE
Add land use capability to our METAR documents

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#209]
Enable the new ingest to store and reference the model land use tables (vgtyp in the grib2 output) in order to use these categorizations as a discriminator. This will need to be a dynamic process, as different models have different land use tables

**Comment by JeffHamiltonNOAA** [comment]
I've reached out to Eric James for the latest land use tables for the operational HRRR and RRFS A/B

**Comment by randytpierce** [comment]
I've created a land_use_types document id MD:LAND_USE_TYPES:COMMON:V01 with all the types I got from Jeff. Next I will create an entry in mats_aux_common "MD:matsAux:COMMON:V01" that will associate each model name with a land_use_type.

**Comment by randytpierce** [comment]
I checked the land_use_types document into the mats_metadata__and_indexes/metadata_files directory along with an import_land_use_types.sh script.

**Comment by randytpierce** [comment]
I added "LAND_USE_TYPE": "MODI-RUC" field to all the primaryModelOrders objects in the "MD:matsAux:COMMON:V01" document. I don't know what all the land_use_type fields are for all the models, but Jeff said he thinks the vast majority will be this type, so to start we can make them all this type and modify ones that are different as needed. This document is updated in the code base, compared to the existing document, and then upserted.

**Comment by randytpierce** [comment]
this is implemented now
