### ISSUE TITLE
ESRL Database RAOB verification

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#224]
## Problem
Require RAOB verification utilizing Mark Govett's RAOB database (to match the legacy system)

## Solution
Processing model and observation data interpolated to standardized pressure and height levels with partial sums generated over predefined regions

## No Go's
This epic will not address RAOB prepBUFR data or any other upper air observation network (aircraft, lidar, etc.)

## Tasks
Describe discrete tasks that need to be done to complete this project

```[tasklist]
- [ ] #225
- [ ] #82
```

**Comment by randytpierce** [comment]
Can this be closed now if we have decided to go 100% prepbufr

**Comment by mollybsmith-noaa** [comment]
No longer relevant
