### ISSUE TITLE
fully implement cfgrib into the grib_to_cb builder

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#226]
Now that we are doing this it needs to be finished hight priority.

**Comment by randytpierce** [comment]
linked an already open branch for this work

**Comment by randytpierce** [comment]
Currently there is an issue with the projection. I have to compare to the original projection generated with pygrib. Unfortunately upgrading the couchbase client is an issue because the latest couchbase client is not backwards compatible to the previous couchbase client requiring a bunch of changes from the main branch to run. Sorting all this out.

**Comment by randytpierce** [comment]
This is pretty much complete except for a review and a little further investigation into why cfgrib DewPoint values aren't the same as pygrib DewPoint values to multiple decimal places. When this gets deployed we need to update the templates to handle two new variables - see https://github.com/NOAA-GSL/VxIngest/issues/208

**Comment by ian-noaa** [comment]
This will also involve the work for #210

**Comment by bonnystrong** [comment]
This is implemented but not deployed and tested.
