### ISSUE TITLE
"data=/opt/data docker compose run int_test" sees Couchbase timeout errors

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#247]
When I run the integration tests from an entry point on my MAC, so that the container will die and go away when the tests finish, I am seeing some Couchbase timeout errors. I think I shouldn't see these. They don't seem to happen when I run the same tests individually from inside a running shell container like...
"data=/opt/data docker compose run shell" then inside the container 
> export PYTHONPATH=`pwd`
> scripts/VXingest_utilities/run_int_tests.sh
......

**Comment by mollybsmith-noaa** [comment]
This is done.
