### ISSUE TITLE
Erroneous values in database for moisture variables

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/VxIngest#261]
Starting mid-December 2021, any plots that involve `sum2_diff` for RH or Dewpoint get really odd:

![newplot-21-11-2023-01_23_27](https://github.com/NOAA-GSL/VxIngest/assets/29582181/558039c5-cd50-4ce5-9a9c-8ba7d8357b46)

For contrast, here is the same plot with the mysql app:

![newplot-21-11-2023-01_20_25](https://github.com/NOAA-GSL/VxIngest/assets/29582181/2e393463-defa-4930-9f3f-35683a6940fc)

Any plots that don't use the Dewpoint or RH `sum2_diff` continue to look normal. Did anything change about this calculation at some point?

**Comment by mollybsmith-noaa** [comment]
Actually, when plotting bias, the RH looks slightly off too (although not dramatically).

MySQL:

![Image](https://github.com/NOAA-GSL/VxIngest/assets/29582181/5ac20bc7-57c0-4e79-adee-945b50d27650)

Couchbase:

![Image](https://github.com/NOAA-GSL/VxIngest/assets/29582181/81a90436-5d83-4fd7-8bd1-9c7b985b68d6)

**Comment by mollybsmith-noaa** [comment]
We're waiting to see if the reprocessed data has this issue as well.

**Comment by mollybsmith-noaa** [comment]
The RH errors are because the METAR obs documents do not contain an RH field at all. It must be backfilled.

**Comment by randytpierce** [comment]
Ok, so Jeff, Molly, and I discussed this and this is how we decided to proceed. 

- [ ]  For whatever reason the data prior to January of 2022 is not reliable. That was very early in our prototyping so we probably ingested some half baked stuff. - **Remove all the documents prior to January 2022.**
- [ ] Modify the netcdf builder to calculate the RH, wind_u, and wind_v values if they don't exist in the netcdf file.
- [ ] make a test that will test the netcdf with a test template and make sure it passes
- [ ] check in the builder - templates won't be calling it yet
- [ ] create a utility (and a utilities dir) in the src tree that will modify obs documents, by epoch range, to add in RH, wind_u, and wind_v if they don't exist in the doc.
- [ ] Test that utility on one doc
- [ ] turn off the ingest cron job
- [ ] run the utility on all the obs
- [ ] modify the obs template to build those vars
- [ ] turn the ingest cron job back on
