### ISSUE TITLE
Re-enable partial sums ingest

### ISSUE THREAD

**Issue by ian-noaa** [NOAA-GSL/VxIngest#267]
We're currently doing a long-running job to backfill the partial sums data in the db. We've disabled the partial sums job in the database while the backfill job is running to prevent spawning multiple similar jobs and clobbering our resources.

Once that job is done on adb-cb1, update the `JOB:V01:METAR:PARTIAL_SUMS:SURFACE:MODEL:HRRR_RAP_130` document and set `status = active`. You can check the job state with `tail -f /data-ingest/data/test/logs/job_v01_metar_partial__sums_surface_model_hrrr__rap__130-2023-11-24:19:03:57.log`. 

Based on some calculation in https://github.com/NOAA-GSL/VxIngest/issues/264#issuecomment-1836477024, I'm anticipating this job will be done running sometime around 2023-12-5.

> As of Friday morning, the partial sums job was still running on adb-cb1 and processing epochs near: 1673632800. (roughly 2023-01-13) The job initially started working on data with epochs near: 1638316800. (roughly 2021-12-1) Given the job was started on 2023-11-24 and has been able to import from December, 2021 to January, 2023 (~14 months in 6 days) I'm guessing this job will continue to run into early next week.
>
> As an aside - the log file for this job has jumped to close to 3 GB. We may want to look into selectively logging so we don't have to spend time troubleshooting disk space issues.

**Comment by ian-noaa** [comment]
Per @randytpierce 

> I wonder how many threads are still running. I.e.  `ps -ef | grep partial_sums | wc -l`
> Initially there were twelve. As they finish they might get archived and imported. So we might be getting partial sums in the database.

It appears that there are 7 ingest processes still running, so we've lost a fair number.
```console
$ ps -ef | grep partial_sums | wc -l
8
```

@randytpierce mentioned that it may be good to revisit how we break up large backfilling jobs like this one.

**Comment by randytpierce** [comment]
It’s hard to guess on this kind of multi-job processes, I agree. I also
agree that Tuesday might be optimistic. Better to wait and see.
Randy

**Comment by ian-noaa** [comment]
The ingest has re-run and the Job doc has been changed to active. Closing.
