### ISSUE TITLE
Create realtime MET TC ingest

### ISSUE THREAD

**Issue by mollybsmith-noaa** [NOAA-GSL/VxIngest#28]
Venita began this project on Jet, but did not get to complete either the realtime rocoto workflow or the database loading. I am currently working to get both of these components up and running.

**Comment by mollybsmith-noaa** [comment]
I have a working realtime workflow that verifies each storm 24 hours after its completion. There are two areas of improvement needed: get the database loading into rocoto (currently in crontab), and create a parallel workflow that verifies storms while they are occurring. Thsi second is blocked until DTC adds the needed functionality to METplus.

**Comment by mollybsmith-noaa** [comment]
DTC has working functionality for verifying TCs at a single valid time, so I can now add that to my workflow. It sounds like the global group places a higher priority on porting the global verification workflows to Hera, though, so I'm going to do that first. Shouldn't take too long.

**Comment by mollybsmith-noaa** [comment]
Things still to do as of 9/7/2021: Add verification for in-progress storms (high priority), add RI stats (medium-high priority), have a more elegant database loading mechanism (low-medium priority; the current one is hideous but it does work and will continue doing so).

**Comment by mollybsmith-noaa** [comment]
Putting this issue on hold, as other things seem to be higher priority

**Comment by mollybsmith-noaa** [comment]
The realtime equivalent of last year's TC verification (which waited until a storm was complete to verify it) is live and working well. It picked up an Invest (AL902022) that began to be forecasted on May 22, and the results were almost immediately available in MET Cyclone! I am currently adding in a workflow to do RI verification, which we did not have at all last year. Because of the way METplus works, this verification does have to be done after the fact, so users will see stats such as track error, intensity error, etc in realtime, and RI verification at a one-week lag. It will still be there, though.

**Comment by bonnystrong** [comment]
What's the status on this?

**Comment by mollybsmith-noaa** [comment]
The most recent update is still current.

**Comment by bonnystrong** [comment]
I would suggest that we break out the RI (Rapid Intensification) into a separate issue and show this as closed.  As we noted in today's team meeting, RI was not part of the original deliverables (which were funded by UFS R2O), which are now 100% complete.

**Comment by mollybsmith-noaa** [comment]
As a developer I like having all of the TC updates in one place, but if it makes things easier from a project management perspective, I can split this up.
