### ISSUE TITLE
Convert units for models and obs to metric values.

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#281]
WindSpeed, DP, and temperature are not metric in current obs and model data records. For consistency we want to make this stuff all metric and let the apps decide how to present the data (doing any necessary conversions). This will require a little thought about how to do this as atomically as possible. Probably need a development instance of Couchbase.

**Comment by randytpierce** [comment]
I re-ran the backfill of METAR obs over the weekend to re-calculate the RH using DegF instead of DegC. The obs should all be good now, to my estimation. The backfill is single threaded and it took about 6 hours. That means that if we want to backfill the model data that we have - like to change the units or to calculate WindU and WindV this single threaded technique would take 2(models) * 48 (fcstLens)  * 6(hours) => 576 hours which I think is probably a no go. So the model backfill will need to be either multi-threaded or broken up into a bunch of different containers that each process a subset of the data. I lean to the later myself.  That would be easy enough. We just need to figure out where to run it. Probably on rancher.

**Comment by mollybsmith-noaa** [comment]
This issue is a copy of #280
