### ISSUE TITLE
Python 3 miniconda environment on Jet

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#29]
I'm attempting to create my own conda environment with Python 3.6 and am getting the following error after the environment is built:

(avid_verify_py3) 114 amb-verif@fe6:~/ensemble/xml$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amb-verif/.conda/envs/avid_verify_py3/lib/python3.6/site-packages/pandas/__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: cannot import name 'core'

I've created the same environment on Hera without issue, so I'm curious if the problem possibly lies with the RDHPCS Ananconda source that is pulling from Jet? I've opened an issue with the Jet SAs and hopefully they will come back with a solution.

**Comment by JeffHamiltonNOAA** [comment]
I've pinged the SAs again. Will wait to hear back. Might reach out to Christina for guidance as well if I don't hear anything in the next day or so.

**Comment by bonnystrong** [comment]
Affects only grid-to-grid on jet.  Molly has a workaround using directory created by Venita. 

Generally a problem with how Python is handled on HPC.  Randy: reason to do it all in a container.

Molly: need to get python and its dependencies for MET which will be a bigger problem.

This may come back to bite us unexpectedly, but hoping that doesn't happen soon!

**Comment by mollybsmith-noaa** [comment]
For reference, the current python version on Hera used for METplus verification (Miniconda avid_verify_py3) is 3.6.12. On Jet (/lfs1/BMC/amb-verif/anaconda3/bin/python3), it is 3.7.5.
