### ISSUE TITLE
Ingest HRRR_OPS grib2 data into CB

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#30]
Create template, builder, and metadata for ingesting HRRR_OPS grib2 data into METAR document types

**Comment by JeffHamiltonNOAA** [comment]
I've created a template document "MD:V01:METAR:ingest:grib2" on adb-cb1 that will serve as a starting point for the builder

**Comment by JeffHamiltonNOAA** [comment]
Working on replicating the grid identification functionality in my own cloned version of the development branch. This will identify HRRR_OPS as a LC projection and find the relevant grid attributes

**Comment by JeffHamiltonNOAA** [comment]
Also working on using the python module PyProj to perform grid transformations. This will be critical in grid-to-obs verification to grab the necessary grid point(s) relevant to a lat-lon coordinate for a particular station

**Comment by randytpierce** [comment]
created a VXingest-issue-30 branch to hold these code code changes.

**Comment by randytpierce** [comment]
This is largely complete, but I traversed the grib files wrongly making it extremely inefficient.
I am closing this issue and creating another issue to track the re-write of the way we use pygib to traverse the model.
That issue is VXingest #32
