### ISSUE TITLE
refactor VxIngest builder code to make more of the code common

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#39]
Once milestone 1.5 is complete we need to refactor the builder classes in VxIngest to derive a common class that will contain any common code, common handlers etc. During this effort we can also implement more unit tests.

**Comment by ian-noaa** [comment]
We had a discussion in our weekly meeting that it may be good to look into setting up dependency management and github actions before doing this as a team. This way it will be easy for other devs to setup their development environments and we will have greater confidence our code is working as intended.

* Setting up Poetry for dependency management is captured in #40 
* Setting up GitHub Actions is captured in #73

**Comment by randytpierce** [comment]
I have intentionally left this task until later for a couple of reasons:
1) I would like to have a design effort with at least Jeff, myself, Ian, and Molly to discuss what is the best way to accomplish this refactoring. I think we should have a parent class over the builders, the ingestMangers, and the thread runner classes. I think  polymorphic approach suits the effort better if the shared library isn't going to be used for other purposes and will be specific to this ingest mechanism, but that should be discussed. That discussion will serve multiple purposes: it will expose key developers to the code, and it may turn up alternatives that I have not thought of.
2) Once we decide on a course of action we should create issues for the work and break the work up. Probably with pair programing.

Overview:
Each ingest process consists of three parts:
top level main is an thread runner - run_ingest_threads.py:VXingest which has one or more...
ingest manager - cx_ingest_manager.py:VxIngestManager which is a thread and has one or more
builder - something_builder.py like grib2_builder.py:GribModelBuilderV01 which actually does the ingest.
There are currently netcdf builders, grib2 builders, and CTC builders.
At each level there exists nearly redundant code that needs to be refactored into common code, possibly in parent classes.

We will be ready to perform this as soon as the 1.5 CTC (ceiling contingency tables) builder is functional and as soon as the github actions exist to run the unit tests on each pull. This issue Set Up GitHub Actions #73 (link above) captures this.

**Comment by randytpierce** [comment]
I have done a significant amount of the code work in a feature branch named after this issue. I will make a pull request and we can review the work together as a group. The task of creating parent classes and understanding which parts of the code should be composition verses polymorphism is complex and I wanted to ply with the concepts in working code before deciding. I think the issue 39 feature branch gives us a good platform for that kind of conversation. In the vxingest paradigm coded in issue 39 we use composition based on the template directive of builder to inform the VxIngestManager what kind of builder to use, but we use polymorphism to allow builder types to be specialized under a general builder parent. For example there is a netcdf builder parent but there is a specialization of netcdf builders for METARS. In the future there may well be other specializations of netcdf builders. It is the same for grib builders and for CTC builders. I haven't created the pull request yet because I was going on vacation and wanted to run the integration tests and review those results first.

**Comment by randytpierce** [comment]
One more note about composition verses inheritance... Composition is often implemented with interfaces, but python doesn't really have a concept of interfaces. What can be done in python is to use a parent class that defines methods to be overridden with the pass keyword. This is essentially how the builders are implemented, i.e. builder.py has a bunch of pass methods that need to be implemented by the specific builders. Not so much the ingest or ingest_managers since they have much more commonality. They are more conducive to inheritance.

**Comment by randytpierce** [comment]
I have merged all of the issue39 code into development because I am going on vacation next week. The code is fully tested. If we find new issues we can deal with them seperately.
