### ISSUE TITLE
Get data model documentation onto our GSL Verification site

### ISSUE THREAD

**Issue by bonnystrong** [NOAA-GSL/VxIngest#54]
Data model is documented with hackolade files that exist in google docs (I believe).  These need to be linked  in our official documentation under the area for "Data Model and NoSQL Databases".  We also need to be sure any google docs are under Jeff's official Vx documentation google folder.

**Comment by randytpierce** [comment]
I added the "Couchbase model RE.json" file to the top level "model" directory in the VXingest project. This is the file that stores the model for Hackolade. I also added a docs directory and a generated markdown document "NWP and obs data documentation.md" that contains the generated documentation. In addition there is a README.md file in the model/docs directiory that gives brief instructions on how to open the model in Hackolade, access the help, and generate documentation.

**Comment by bonnystrong** [comment]
Our official documentation repository is the Google site.  Jeff also owns our "virtual team drive" in google docs.  He needs to get the data model into the virtual team drive and on the google site.  So I'm reopening this.

**Comment by JeffHamiltonNOAA** [comment]
The Couchbase Data Model documentation PDF generated by Hackolade is in the shared Team folder on Google Drive. I've requested access to the Google Sites area to ensure it shows up there as well. Will wait for that and confirm before closing

**Comment by bonnystrong** [comment]
It is now on the Google site on the Data Model and NoSQL Databases page.  The problem was that it was previously pointing to a drive in my Google drive area that no one else could access.  I could not find a way to modify it, so I deleted it and recreated it using our Vx virtual team drive.

I think it would be good to add a very short description of what Hackolade is, where to find it, version needed, and name of our model (which I can't remember, "snow"?)
