### ISSUE TITLE
Only send encrypted passwords from Python SDK to Couchbase Server

### ISSUE THREAD

**Issue by venitahagerty** [NOAA-GSL/VxIngest#58]
It looks like we can either:

Not use LDAP connections to the Couchbase server
Use a LetsEncrypt certificate for the Couchbase server
Not use certificates in the Python SDK

or

Use LDAP connections to the Couchbase server
Use a self-signed certificate for the Couchbase server
Use self-signed certificates in the Python SDK

I'm not sure what LDAP buys us, if anything. Kirk added it to the newer Couchbase clusters, we didn't have it on the original ones.

What I would like to do is discuss this with the instructor during the Couchbase Administration class (currently March 9-12) before making a decision.

**Comment by bonnystrong** [comment]
Moved this issue from VxData to VxIngest.  Reassigning to Randy with Venita's departure.

**Comment by randytpierce** [comment]
I think we are ok on this for now. Dave Haggerty is managing certificates for the web interface and the client interface is totally internal so I want to close this issue and stop tracking it for now.
