### ISSUE TITLE
Specify isobaric levels for each model

### ISSUE THREAD

**Issue by JeffHamiltonNOAA** [NOAA-GSL/VxIngest#67]
In the legacy ingest, upper air isobaric verification was done using assumptions in the code as to what levels existed inside the model grib2 output. Ensure that this does not happen when designing the new UA ingest and work to find another solution, whether it be in model configuration or in pygrib file quering.

**Comment by bonnystrong** [comment]
Needs to be considered with design of Upper Air in new ingest.

Different models have different methods of indicating this.

**Comment by JeffHamiltonNOAA** [comment]
Working on this as part of the 3D data model work

**Comment by bonnystrong** [comment]
Will interpolate to every 10 mbars.
