### ISSUE TITLE
make changes to obs ingest such that early and delinquent observations that are off by more than 30 minutes get moved to the previous or later document

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#69]
make changes to obs ingest such that early and delinquent observations that are off by more than 30 minutes get moved to the previous or later document.

More description is forthcoming

**Comment by bonnystrong** [comment]
Adding Dave Turner's email comments from 10/21 and 10/22

10/21
   I dug into the problem we were discussing during the VxIngest meeting more.  My initial impression was not correct; the METAR data (in /public/data/madis/point/metar/netcdf) is actually good.  What we are seeing is that the different stations are queried (i.e., provide an observation) a different number of times each hour.  Unfortunately, all of these queries are then assigned the same "timeNominal" value (even though they each have their own unique "timeObs" value).

  The two attached figures illustrate this.  The red dots have only a single sample per hour, green are two samples per hour, and green are 3 samples per hour (I did not see any stations that were sampled more frequently than 3 / hour).  So ultimately, we need to find the observation that is closest to the model valid time, and ignore the others.  Generally speaking, I think this is the first observation for a given site in  the file; however, I haven't really proven this to myself fully.  

![global_sampling](https://user-images.githubusercontent.com/29129914/138534032-abe3eef1-bb5b-446d-b8d8-fff0d97a2d1b.png)
![NA_sampling](https://user-images.githubusercontent.com/29129914/138534043-38a2a8dd-3146-4970-bb80-ab7ee4bbcd6a.png)

10/22
   A small tweak to your logic: I think we want to select the observation where the timeObs is closest to the model valid time.  I am not sure that timeNominal really has any value for us.  We need to be sure not to assume (in our software structure) that model valid times are hourly; I can imagine that in the future we might want to validate higher temporal resolution model output more routinely.  

  Eventually, we might want to consider including some sort of logic to interpolate the observations over time to exactly the model valid time, but let's table that activity for a while.

**Comment by JeffHamiltonNOAA** [comment]
We've made the collective decision that only the obs that are closest to the valid hour (top of the hour in this case) from a single file will be included. We will track the number of reports for a station that are outside of the time binning thresholds only if it is the only report in that file. If the number of reports that fall into that criteria exceed ~5%, we flag a developer to investigate. This issue can now be closed
