### ISSUE TITLE
determine how legacy code deals with metar observation timeObs values that are greater than +- 30 from nominal.

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#71]
determine how legacy code deals with metar observation timeObs values that are greater than +- 30 from nominal.

We need to know what the legacy code does in the case where a metar observation is greater than 30 seconds away from the valid time. This issue blocks issue 69

**Comment by JeffHamiltonNOAA** [comment]
This issue can now be closed
