### ISSUE TITLE
Determine why there are a few observation values that do not agree between legacy and cb systems with legacy calling out 6000 and cb calling out None

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#76]
Running the test case test_ctc_builder_hrrr_ops_all_hrrr_compare_model_obs_data (example below) will produce output of the measured differences that can be evaluated. This is how I run the test from the command line and capture the output.
 python3 -m pytest -s -v  /Users/randy.pierce/PycharmProjects/VXingest/ctc_to_cb/test/test_metar_ctc.py::TestCTCBuilderV01::test_ctc_builder_hrrr_ops_all_hrrr_compare_model_obs_data > test_result_ctc_compare.txt

This grep "grep obs test_result_ctc_compare.txt"
will output the observation differences.
Some of these differences are where the legacy has 60000 (really 6000) but the cb has identified "None"
example....
1643 obs 1636322400 18 3000 KTNB 60000 None 6000
They can be found with this grep...
"grep obs test_result_ctc_compare.txt | grep None"
pierce-lt:VXingest randy.pierce$ grep obs test_result_ctc_compare.txt | grep None
1643 obs 1636322400 0 500 KTNB 60000 None 6000
1643 obs 1636322400 0 1000 KTNB 60000 None 6000
1643 obs 1636322400 0 3000 KTNB 60000 None 6000
1643 obs 1636322400 0 60000 KTNB 60000 None 6000
1643 obs 1636322400 1 500 KTNB 60000 None 6000
1643 obs 1636322400 1 1000 KTNB 60000 None 6000
1643 obs 1636322400 1 3000 KTNB 60000 None 6000
1643 obs 1636322400 1 60000 KTNB 60000 None 6000
1643 obs 1636322400 3 500 KTNB 60000 None 6000
1643 obs 1636322400 3 1000 KTNB 60000 None 6000
1643 obs 1636322400 3 3000 KTNB 60000 None 6000
1643 obs 1636322400 3 60000 KTNB 60000 None 6000
1643 obs 1636322400 6 500 KTNB 60000 None 6000
1643 obs 1636322400 6 1000 KTNB 60000 None 6000
1643 obs 1636322400 6 3000 KTNB 60000 None 6000
1643 obs 1636322400 6 60000 KTNB 60000 None 6000
1643 obs 1636322400 9 500 KTNB 60000 None 6000
1643 obs 1636322400 9 1000 KTNB 60000 None 6000
1643 obs 1636322400 9 3000 KTNB 60000 None 6000
1643 obs 1636322400 9 60000 KTNB 60000 None 6000
1643 obs 1636322400 12 500 KTNB 60000 None 6000
1643 obs 1636322400 12 1000 KTNB 60000 None 6000
1643 obs 1636322400 12 3000 KTNB 60000 None 6000
1643 obs 1636322400 12 60000 KTNB 60000 None 6000
1643 obs 1636322400 15 500 KTNB 60000 None 6000
1643 obs 1636322400 15 1000 KTNB 60000 None 6000
1643 obs 1636322400 15 3000 KTNB 60000 None 6000
1643 obs 1636322400 15 60000 KTNB 60000 None 6000
1643 obs 1636322400 18 500 KTNB 60000 None 6000
1643 obs 1636322400 18 1000 KTNB 60000 None 6000
1643 obs 1636322400 18 3000 KTNB 60000 None 6000
1643 obs 1636322400 18 60000 KTNB 60000 None 6000

We need to understand why this one station seems to result in the legacy calling out 6000 and the CB ingest calling out None.

**Comment by JeffHamiltonNOAA** [comment]
I have discovered the reason for the discrepancy between some MySQL stations having ceiling values, but Couchbase includes them as Nones. In the legacy system, there is a secondry step to transform cloud layer identifiers into a ceiling value. During this process, the query searches for the nearest VALID ceiling value to the interpolated time. The cases we are seeing are when the closest observation report to the interpolated time does not include a ceiling value (NULL in SQL), but there is another report for that station within the time binning that does. The old code automatically grabs that value EVEN THOUGH IT IS NOT THE SAME REPORT AS THE REMAINING SURFACE VARIABLES, meaning winds, temperature, dew point, etc. could not be an accurate representation of the state during which the cloud ceiling was reported when looking at the entire picture. We'll need to discuss this as a group because it is one thing to do this when the verification for surface variables and ceiling is separated, but it is quite another when working in the process-oriented realm.

**Comment by randytpierce** [comment]
Wow, thanks,
I could probably have never figured that out.
It seems that there are three possibilities.
1) Make it work the legacy way (which I agree is not what we want for process oriented going forward)
2) Make it work the new way from here on out
3) Create a new field that has the legacy value in the document (the one interpolated within the bin but not within the +- 30 minute interval) for the purpose of convincing ourselves that our code is correct.

**Comment by JeffHamiltonNOAA** [comment]
After meeting with Bonny, Dave, and Molly last week, we have a path forward. In our new ingest, we will use the closet report to the interpolation time even if the ceiling is not included there. However, in order to perform comparison testing with the MySQL database, we will create a new branch called "mysql_comparison" where I will adapt the code to look for the nearest valid ceiling value to the top of the hour (if one exists). This should remove the final observation differences between the two systems, allowing us to move forward with the new paradigm.

**Comment by randytpierce** [comment]
Jeff and I discussed this at length today in an effort to determine the best way to implement the code changes. We decided that an appropriate approach in the code is to create a new builder that inherits from the current netcdfObsBuilder and overrides the load_data method in order to add the ceiling value that is valid and closest to the fcstValidLength epoch even if it does not have the same record time as the rest of the data element that goes with a particular station. 

This approach will allow us to create a new ingest document with the subset "metar-legacy" and use another load spec to invoke this new builder. All the rest of the code remains the same. We need an additional cron entry to run the new load spec. The new builder class, ingest document, and load spec are written but not yet tested. When tested and implemented this new ingest will create documents that are identified by an id that includes the subset "metar-legacy".

These new documents will have a data map with elements that have a ceiling value that should match the legacy ceiling values and they will also have a ceiling_recrd_time that has the record time of the netcdf record which contains the ceiling value that actually gets set in the document, because the ceiling value might come from a different netcdf record than the rest of the data element.

We can test these documents in a couple of ways. We can use the test case to validate the data, and we can potentially add a selector to the cb-ceiling app that switches between the two sets of data, allowing side by side comparison to the existing ceiling app. When we are ready the data will also be easy to find and delete. It is also possible to change the model names from something like "HRRR_OPS" to something like "HRRR_OPS-LEGACY" and that would require no changes to the app.

This is an interesting approach because it sort of validates the concept of using the framework to make quick changes to the ingest without having to change a lot of structure. It also validates the idea of modifying data for temporary purposes by changing an ingest document and providing a subclass. I think is a step to further explore the process oriented approach.

The code change for the new builder required about 100 lines of code approximately half of which were comments.

**Comment by randytpierce** [comment]
The part in the previous comment about " It is also possible to change the model names from something like "HRRR_OPS" to something like "HRRR_OPS-LEGACY" and that would require no changes to the app." is utter nonsense. I must have started happy hour early. These are observations. We must rely on the subset being "METAR-LEGACY" and that will need to carry through to the CTC documents that are generated for "METAR-LEGACY" observations. We will have two sets of observations and two sets of ceiling CTC's identified by their subset being "METAR-LEGACY".  The CTC documents do have a model and we might be able to make their model something like "HRRR_OPS-LEGACY" and that might make it unnecessary to change the cb-ceiling app while still being able to compare to legacy data.

**Comment by davidturner53** [comment]
Sorry -- I hit the wrong button here!  Issue should still be open.

**Comment by JeffHamiltonNOAA** [comment]
Since we have an explanation for the problem and have determined the path forward, I will close this issue and aloow Randy to update on implementation of the fix in issue #75
