### ISSUE TITLE
reprocess HRR_OPS_LEGACY_RETRO data

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/VxIngest#89]
We need to make a new subset of data that comes from the madis archive. We are going to call it subset METAR-LEGACY-RETRO
and the valid date range is dec 1 through 7 2021

**Comment by randytpierce** [comment]
Notes from chat...
SELECT *
FROM mdata
WHERE mdata.type='MD'
    AND mdata.docType = "station"
    AND mdata.version='V01'
    AND mdata.subset='METAR'
LIMIT 10
Molly Smith - NOAA Affiliate12:15 PM
select madis_id,name,lat,lon,elev,description from metars_mats_global where lat > -16380 and lat < 16380 and lon > -32760 and lon < 32760 order by name;
Jeffrey Hamilton - NOAA Affiliate12:27 PM
/lfs4/BMC/amb-verif/backfill/hrrr_ops/

**Comment by JeffHamiltonNOAA** [comment]
I have downloaded the MADIS METAR data for this period and placed it in the dedicated qumulo disk space to be used for Couchbase loading from HPC (qumulo1.gsd.esrl.noaa.gov:/adb-mdb/couchbase/xfer). I'm unsure if this area is visible from adb-cb1 as it is not mounted in the same place as it is on emb-prod-verif. If not, I will load it onto cb1 in an area that Randy is comfortable with.

**Comment by randytpierce** [comment]
This was accomplished in several steps.
1) had Gary implement the mount...
qumulo1.gsd.esrl.noaa.gov:/adb-mdb/couchbase/xfer on /couchbase/xfer type nfs (ro,noatime,nodiratime,vers=3,rsize=1048576,wsize=1048576,namlen=255,acregmin=15,acdirmin=45,acdirmax=90,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=137.75.161.38,mountvers=3,mountport=2049,mountproto=tcp,local_lock=none,addr=137.75.161.38)

which gives adb-cb1 access to the data that Jeff retrieved from tape.

2) Created ingest documents for METAR_RETRO MD:V01:METAR-RETRO:obs:ingest:netcdf which uses the METAR_LEGACY builder to build documents with a subset of "METAR-RETRO"

3) ran the ingest. This only needed to be done once since this is a static dataset. I created a script scripts/VXingest_utilities/run-metar-retro-ingest.sh  for this purpose.

4) created an integration test case that can print out the results of comparing the METAR-LEGACY subset to the METAR_RETRO subset in a format that can be analyzed. The test case is  run on adb-cb1 by 
> source ~/vxingest-env/bin/activate
> cd ~/VxIngest
> export PYTHONPATH=`pwd`
> python3 -m pytest -s -v  netcdf_to_cb/test/test_int_metar_obs_netcdf.py::TestNetcdfMetarLegacyObsBuilderV01::test_compare_legacy_obs_to_metar_retro > ~/test_result_metar-retro.txt

5) analyze the results? 
to get a list of only deltas...
>  grep "^var" ~/test_result_metar-retro.txt | awk '{if ($6 != 0.0 && $6 != "None") {print $0}}' > ~/test_result_metar-retro_diffs_only.txt
to produce histograms of those ...
>  python netcdf_to_cb/test/delta_hist.py -f ~/test_result_metar-retro_diffs_only.txt
to see how many uniq fcst times there are in the differences...
> awk '{print $9}' ~/test_result_metar-retro_diffs_only.txt | sort | uniq | wc
to see how many uniq stations there...
>awk '{print $8}' ~/test_result_metar-retro_diffs_only.txt | sort | uniq | wc

Now I need to discuss this all with Jeff.

**Comment by randytpierce** [comment]
Some interesting observations about the retro data.
How many valid times are in the retro?
> awk '{print $9}' ~/test_result_metar-retro.txt | sort | uniq | wc
    189     188    1969
*189*
How many of those end up in the diffs report?
> awk '{print $9}' ~/test_result_metar-retro_diffs_only.txt | sort | uniq | wc
     45      45     495
*45*
How many stations in the full retro?
> awk '{print $8}' ~/test_result_metar-retro.txt | sort | uniq | wc
   2598    2597   12999
*2598*
How many stations have diffs?
> awk '{print $8}' ~/test_result_metar-retro_diffs_only.txt | sort | uniq | wc
    342     342    1710
*342*

create histograms of the diffs? (must be done on a system with browsers and plotly installed)
> python netcdf_to_cb/test/delta_hist.py -f ~/test_result_metar-retro_diffs_only.txt

**Comment by randytpierce** [comment]
So after discussing it today I determined that I had neglected to strip out the stations that had been determined to be problematic for the projection algorithm. Those stations are in the document MD-TEST:V01:LEGACY_REJECTED_STATIONS.

I made this change and re-ran the test.
[amb-verif@adb-cb1 ~]$ cd VxIngest/
[amb-verif@adb-cb1 VxIngest]$ source ~/vxingest-env/bin/activate
(vxingest-env) [amb-verif@adb-cb1 VxIngest]$ export PYTHONPATH=pwd
(vxingest-env) [amb-verif@adb-cb1 VxIngest]$ python3 -m pytest -s -v netcdf_to_cb/test/test_int_metar_obs_netcdf.py::TestNetcdfMetarLegacyObsBuilderV01::test_compare_legacy_obs_to_metar_retro > ~/test_result_metar-retro.txt

Here are the results ....
The total number of observations:
[amb-verif@adb-cb1 ~]$ wc -l test_result_metar-retro.txt
3823466 test_result_metar-retro.txt

the total number of diffs:
[amb-verif@adb-cb1 ~]$ wc -l test_result_metar-retro_diffs_only.txt 
1262 test_result_metar-retro_diffs_only.txt

The number of diffs per variable:
[amb-verif@adb-cb1 ~]$ grep Temperature ~/test_result_metar-retro_diffs_only.txt | wc -l
465
[amb-verif@adb-cb1 ~]$ grep DewPoint ~/test_result_metar-retro_diffs_only.txt | wc -l
461
[amb-verif@adb-cb1 ~]$ grep WD ~/test_result_metar-retro_diffs_only.txt | wc -l
300
[amb-verif@adb-cb1 ~]$ grep WS ~/test_result_metar-retro_diffs_only.txt | wc -l
100
[amb-verif@adb-cb1 ~]$ grep Visibility ~/test_result_metar-retro_diffs_only.txt | wc -l
13
[amb-verif@adb-cb1 ~]$ grep Ceiling ~/test_result_metar-retro_diffs_only.txt | wc -l
5
[amb-verif@adb-cb1 ~]$ grep Surface_Pressure ~/test_result_metar-retro_diffs_only.txt | wc -l
1

The total number of validEpochs  in the retro:
[amb-verif@adb-cb1 ~]$ awk '{print $9}' ~/test_result_metar-retro.txt | sort | uniq | wc -l
189

The total number of validEpochs with diffs:
[amb-verif@adb-cb1 ~]$ awk '{print $9}' ~/test_result_metar-retro_diffs_only.txt | sort | uniq | wc -l
45

The total number of stations in the retro:
[amb-verif@adb-cb1 ~]$ awk '{print $8}' ~/test_result_metar-retro.txt | sort | uniq | wc -l
2598
The total number of stations with diffs:
[amb-verif@adb-cb1 ~]$ awk '{print $8}' ~/test_result_metar-retro_diffs_only.txt | sort | uniq | wc -l
342

**Comment by randytpierce** [comment]
This is now working but I'm not closing it until a little further discussion about the diffs.

**Comment by JeffHamiltonNOAA** [comment]
I've put this explanation in issue #77 but will place it here as well:

We are comparing the operational HRRR and MADIS archive data in both the CB and SQL databases over two different two weeks periods, one from July 1-15 2021 and the other December 1-15 2021. This test will exclude the stations that are grabbing different nearest neighbors using the two projection transformation methods and will use the SQL version of grabbing the nearest valid ceiling value (if one exists) instead of the value (or NaN) that corresponds to the nearest report to the valid time (the model name for this methodology will be HRRR_OPS_LEGACY_RETRO in both CB and SQL). With these comparisons, we intend to establish a baseline for thresholds of difference (mean, standard dev., etc) to use moving forward

**Comment by randytpierce** [comment]
We are going to compare two sets of retro data, first 2 weeks in July 2021 and first 2 weeks in December. To reload the model data I am creating a small wrapper script to read the model data from AWS. Jeff is working on retrieving the MADIS obs files.

**Comment by randytpierce** [comment]
This is finished ingesting, and the testing of it is covered under a different issue so this issue is effectively finished. The retro work has turned up another problem with the legacy ingest but I am deferring that problem to Jeff.
