### ISSUE TITLE
Add ECMWF analysis as truth in grid-to-grid METexpress app

### ISSUE THREAD

**Issue by davidturner53** [NOAA-GSL/VxIngest#94]
There is a desire to have the ability to use both GFS analysis (currently implemented) and the ECMWF analysis (needed) as the truth dataset in the METexpress grid-to-grid app.  We need to see if the DSG is already bringing in this EC analysis; if so, we need to inquire about getting it.  Then we need to estimate the amount of effort needed to get this dataset included in our processing.  Then we can adjust the priority relative to other tasks.

**Comment by mollybsmith-noaa** [comment]
Duplicate issue and already done!
